# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### Send POST request with json body
POST https://httpbin.org/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###

POST http://localhost:5000/flask_microservice/user
Content-Type: application/json

{
  "username": "foo2",
  "password": "bar",
  "emailaddress": "foo2@fighters.mu"
}

###

GET http://localhost:5000/flask_microservice/user/foo2@fighters.mu

###

GET https://nfr9ihl8ek.execute-api.us-east-1.amazonaws.com/flask_microservice/flask_microservice/user/foo2@fighers.mu

###


